#!/bin/sh

output="$1"

nuforce () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default nuforce
ctl.!default nuforce
EOF
}

aengine () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default aengine
ctl.!default aengine
EOF
}

thinkpad () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default thinkpad_hw
ctl.!default thinkpad
EOF
}

wine () { # nuforce w/o dmix
    cat > ~jae/.asoundrc.default << EOF
pcm.!default winegame
ctl.!default nuforce
EOF
}

usage () {
    echo `basename $0` '[wine|nuforce|aengine|thinkpad|auto]'
}

case $output in
    w*) wine ;;
    n*) nuforce ;;
    t*) thinkpad ;;
    a*) asound-set ;;
    *) usage ;;
esac

