#!/bin/sh

set -e

iam=$0
src="$1"

case $iam in
    anything-to-mp3)
        dst=${1%.*}.mp3
        ffmpeg -i $src -acodec libmp3lame -aq 1 $dst
        #avconv -i $src -acodec libmp3lame -aq 1 $dst
        ;;
    anything-to-wav)
        dst=${1%.*}.wav
        ffmpeg -i $src -acodec pcm_s16le -ac 2 $dst
        ;;
esac


