#!/bin/zsh
#
# Automates retraining of bogofilter.
#
# Appends together ham/spam into 2 mboxes and feeds those to training program
# (bogominitrain.pl at the moment). 
#
# Cleans up tmp training mboxes. 

ham_files=(agents comm domain drdobbsjournal family/knoll family/srobin facebook friends games ham howto inbox jobhunt list-info mlists nvidia openbox pypy python root rxvt-unicode srobin starship zmysqlda zsh work/inbox work/tips work/kavi)

ham=()
for hf in $ham_files; do
    ham+=(~/Mail/$hf)
done

for file in ~/Mail/sentmail/*(.); do
    ham+=($file)
done

# spam is much simpler as I collect my spam in one place
spam=(~/Mail/spam-training)

hamfile=~/.tmp/ham
spamfile=~/.tmp/spam

rm -f $hamfile
rm -f $spamfile

for file in $ham; do
    if [ -d "$file" ]; then
	find "$file" -type f | while read f; do
	    cat $f | formail >> $hamfile
	done
    else
	cat $file >> $hamfile
    fi
done

for file in $spam; do
    cat $file >> $spamfile
done

bogotrain=~/bin/bogominitrain.py
#echo "perl $bogotrain -fnv -b '-o 0.95,0.35' $hamfile $spamfile"
#perl $bogotrain -fnv -b '-o 0.95,0.35' $hamfile $spamfile
echo "$bogotrain -fnv -b '-o 0.95,0.35' $hamfile $spamfile"
$bogotrain -fnv -b '-o 0.95,0.35' $hamfile $spamfile
echo 'done. removing tmp files'
rm $hamfile
rm $spamfile




# This was a bit to clean spamassassin headers off my email so it wouldn't
# screw with training the bayesian filters. Btw, I was unimpressed with
# spamassassin (used it for about a year).
#
#cleandir=Mailclean
#backdir=Mailback
## clean spamassassin headers from email
#for file in Mail/*(.); do
#    echo -n "starting processing $file..."
#    cp $file $backdir/${file#Mail/}
#    formail -s spamassassin -d < $file > $cleandir/${file#Mail/}
#    mv $cleandir/${file#Mail/} $file
#    echo "done"
#done

