#!/bin/zsh

usage () {
    echo "Usage: `basename $0` COMMAND [options]"
    echo "COMMANDs:"
    echo "usb    - sync all music to usb drive (/media/data)"
    echo "hd     - sync goodlist playlist songs to local drive."
    echo "player - sync goodlist playlist songs to Sansa."
}

# take all current songs in playlist, hardlink to a tmp dir and swap dirs
rm_old () {
    src=$1
    [ -d "$src" ] || { echo "Missing source directory"; usage; exit 1; }

    tmpdir="$src/.tmp"
    mkdir -p $tmpdir

    (
        cd $src
        cat ~/.mpd/playlists/goodsongs.m3u | while read f ; do
            cp --link --parent "$f" "$tmpdir/"
        done
    )

    rm -rf $src/artists $src/mixed
    mv "$tmpdir/*" $src
    rmdir $tmpdir
}

case "$1" in
    usb)
        echo "Verify mount:"
        mount | grep media
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        rsync -vaiz --progress --size-only \
            /share/public/music/{artists,mixed,jazz} /media/data/music/
        ;;
    hd)
        echo "Verify NFS mount:"
        mount | grep "^nfs"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        rsync -viz --size-only --progress \
            --files-from ~/.mpd/playlists/goodsongs.m3u \
            /share/public/music /home/jae/Shelf/music
        #rm_old /home/jae/Shelf/music
        ;;
    player)
        MOUNT=/media/data/sdb
        echo "Verify mount:"
        mount | grep "$MOUNT"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        rsync -viz --progress --size-only \
            --files-from ${HOME}/.mpd/playlists/goodsongs.m3u \
            /share/public/music $MOUNT/MUSIC/playlist/
        cp ${HOME}/.mpd/playlists/goodsongs.m3u $MOUNT/MUSIC/playlist/
        sed -i 's/\//\\/g' $MOUNT/MUSIC/playlist/goodsongs.m3u 2> /dev/null
        ;;
    *) usage ;;
esac


