#!/bin/zsh

usage () {
    echo "Usage: `basename $0` COMMAND [options]"
    echo "COMMANDs:"
    echo "usb    - sync all music to usb drive (/media/data)"
    echo "hd     - sync goodlist playlist songs to local drive."
    echo "player - sync goodlist playlist songs to Sansa."
}
short-usage () {
    echo "hd player usb"
}

# take all current songs in playlist, hardlink to a tmp dir and swap dirs
rm_old () {
    set -e
    src=$1
    [ -d "$src" ] || { echo "Missing source directory"; usage; exit 1; }

    olddir="$src/old"
    mkdir $olddir

    mv $src/artists $src/mixed $olddir/

    (
        cd $olddir
        cat ~/.mpd/playlists/goodsongs.m3u | while read f ; do
            cp --link --parent "$f" "$src/"
        done
    )

    [ -d $olddir ] && rm -rf $olddir
}

case "$1" in
    usb)
        MOUNT=/media/data/music
        echo "Verify mount ($MOUNT):"
        mount | grep media
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        rsync -vaiz --progress --size-only --delete \
            /share/public/music/{artists,mixed,jazz} $MOUNT/
        ;;
    hd)
        MOUNT=/share/public
        echo "Verify NFS mount ($MOUNT):"
        mount | grep "^nfs"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        set -e
        rsync -viz --size-only --progress --delete \
            --files-from ~/.mpd/playlists/goodsongs.m3u \
            $MOUNT/music /home/jae/shelf/music
        rm_old /home/jae/shelf/music
        ;;
    player)
        MOUNT=/media/data/sdb
        echo "Verify mount: ($MOUNT)"
        mount | grep "$MOUNT"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        cp ${HOME}/.mpd/playlists/goodsongs.m3u $MOUNT/MUSIC/playlist/
        sed -i 's/4a$/p3/g' $MOUNT/MUSIC/playlist/goodsongs.m3u 2> /dev/null
        rsync -viz --progress --size-only --delete \
            --files-from $MOUNT/MUSIC/playlist/goodsongs.m3u \
            /share/public/music $MOUNT/MUSIC/playlist/
        sed -i 's/\//\\/g' $MOUNT/MUSIC/playlist/goodsongs.m3u 2> /dev/null
        ;;
    list) short-usage ;;
    *) usage ;;
esac


