#!/bin/sh

# XXX  change to use fping

# kavi - 66.179.20.222
# google - 64.233.187.99
# isp nameserver - 
#   primary 209.225.8.42
#   secondary 24.240.141.241 - filtered, don't use
#
#IP=68.180.206.184 # yahoo
IP=69.147.114.224 # yahoo
AIP=64.233.187.99 # google
GIP=68.118.117.233
ping=
count=1
interval=1
timeout=2
cmd=`basename $0`

usage () {
    echo "usage: $cmd [options] [IP]"
    echo "-i ping interval"
    if [ "$cmd" = "upyet" ]; then
        echo "-p ping"
        echo "-c N count N times"
    else
        echo '-w response timeout'
    fi
    echo "-a alternate IP"
    echo "-g ISP gateway"
    exit 0
}

while getopts aghpi:c:w: arg; do
    case $arg in
        p) ping=true; [ $count -eq 1 ] && count= ; shift;;
        c) count=$OPTARG; shift; shift;;
        i) interval=$OPTARG; shift; shift;;
        a) IP=$AIP; shift;;
        g) IP=$GIP; shift;;
        w) wait=$OPTARG; shift;;
        h) usage;;
    esac
done
# non-flagged arg is IP/host
[ -n "$1" ] && IP=$1

if [ "$cmd" = "downyet" ]; then
    /bin/ping -W $timeout -i $interval $IP
    exec /usr/bin/play ~/.themes/sounds/thunder.wav;
else
    if [ -n "$ping" ] ; then
        if [ -n "$count" ]; then
            echo /bin/ping -i $interval -c $count $IP
            /bin/ping -i $interval -c $count $IP
        else
            /bin/ping -i $interval $IP
        fi
    else
        date;
        until /bin/ping -i $interval -q -c $count $IP; do
            sleep 5;
            date;
        done
        exec /usr/bin/play ~/.themes/sounds/itsawak2.wav;
    fi
fi

#/usr/bin/aplay /usr/local/share/sounds/hamster.au;
## vim: expandtab
