#!/bin/sh

# Author: John Eikenberry <jae@zhar.net>
# License: GPL 3.0 <http://www.gnu.org/licenses/gpl.txt>

# XXX  change to use fping

# kavi - 66.179.20.222
# google - 64.233.187.99
# isp nameserver - 
#   primary 24.197.160.17
#   secondary 24.197.160.18
#
#IP=68.180.206.184 # yahoo
IP=69.147.122.70 # yahoo
AIP=74.125.157.147 # google
GIP=68.118.117.233 # gateway
VPSIP=68.68.99.138 # draal
ISP=24.197.160.17 # isp nameserver

flip=
simpleping=
count=1
interval=1
timeout=2
cmd=`basename $0`
delay=1
adapt=

ARGS="$@"
usage () {
    echo "usage: $cmd [options] [IP]"
    echo "-i ping interval"
    echo "-s sleep delay"
    if [ "$cmd" = "upyet" ]; then
        echo "-p ping"
        echo "-c N count N times"
        echo "-A use Adaptive ping"
    else
        echo '-t response timeout'
        echo '-f flip to upyet when down'
    fi
    echo "-a alternate IP"
    echo "-g ISP gateway"
    echo "-v my vps at prgmr.com"
    echo "-n isp nameserver"
    exit 0
}

while getopts aAnvfghpi:c:t:s: arg; do
    case $arg in
        A) adapt=true; shift;;
        p) simpleping=true; [ $count -eq 1 ] && count= ; shift;;
        c) count=$OPTARG; shift; shift;;
        i) interval=$OPTARG; shift; shift;;
        a) IP=$AIP; shift;;
        v) IP=$VPSIP; shift;;
        n) IP=$ISP; shift;;
        f) flip=true; shift;;
        g) IP=$GIP; shift;;
        t|w) timeout=$OPTARG; shift; shift;;
        s|d) delay=$OPTARG; shift; shift;;
        h) usage;;
    esac
done

# non-flagged arg is IP/host
[ -n "$1" ] && IP=$1

ERR="\033[0;31m"
HIT="\033[1;32m"
RST="\033[0m"

report () {
    echo "$cmd:\tpings:\t$total\tmisses:$totalmiss"
    trap '' 0
    [ "$1" = "exit" ] && exit
}

ping='/bin/ping'

if [ "$cmd" = "downyet" ]; then
    trap 'report exit' 0 2
    miss=0
    total=0
    totalmiss=0
    until [ $miss -ge 2 ]; do
        total=$(($total + 1))
        if ! $ping -q -W $timeout -c $count $IP > /dev/null; then
            miss=$(($miss + 1))
            totalmiss=$(($totalmiss + 1))
            echo "${ERR}"`date`"${RST}";
        else
            miss=0
            echo "${HIT}"`date`"${RST}";
        fi
        sleep $delay;
    done

    if [ -n "$flip" ]; then
        /usr/bin/play -q ~/.themes/sounds/thunder.wav &
        echo "${ERR}-------------------- DOWN --------------------${RST}"
        report
        sleep $delay;
        exec upyet "$ARGS"
    else
        exec /usr/bin/play -q ~/.themes/sounds/thunder.wav
    fi
else
    ping="$ping -i $interval"
    [ "$adapt" = "true" ] && ping="$ping -A"

    if [ -n "$simpleping" ] ; then
        if [ -n "$count" ]; then
            echo $ping -c $count $IP
            $ping -c $count $IP
        else
            $ping $IP
        fi
    else
        date;
        until $ping -q -c $count $IP; do
            sleep $delay;
            date;
        done

        if [ -n "$flip" ]; then
            /usr/bin/play -q ~/.themes/sounds/itsawak2.wav &
            echo "${HIT}-------------------- UP --------------------${RST}"
            exec downyet "$ARGS"
        else
            exec /usr/bin/play -q ~/.themes/sounds/itsawak2.wav
        fi
    fi
fi

#/usr/bin/aplay /usr/local/share/sounds/hamster.au;
## vim: expandtab
