#!/bin/sh

# I play at being an audiophile sometimes so I have multiple external DACs.
# This lets me set which one ALSA defaults to.

output="$1"

# my first DAC, nuforce uDAC2
nuforce () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default nuforce
ctl.!default nuforce
EOF
}

# Audioengine D1 DAC
# better reviewed than the nuforce, I agree
aengine () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default aengine
ctl.!default aengine
EOF
}

# steam/borderlands-2 liked this setting
aengine48 () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default aengine48
ctl.!default aengine
EOF
}

# if I'm desperate
thinkpad () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default thinkpad_hw
ctl.!default thinkpad
EOF
}

# wine really hates dmix
wine () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default winegame
ctl.!default aengine
EOF
}

usage () {
    echo `basename $0` '[wine|nuforce|aengine|thinkpad|auto]'
}

case $output in
    w*|g*) wine ;;
    n*) nuforce ;;
    t*) thinkpad ;;
    a48) aengine48 ;;
    auto|a*) asound-set ;;
    *) usage ;;
esac

