#!/bin/sh

output="$1"

nuforce () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default nuforce
ctl.!default nuforce
EOF
}

aengine () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default aengine
ctl.!default aengine
EOF
}

# borderlands-2 liked this best
aengine48 () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default aengine48
ctl.!default aengine
EOF
}

thinkpad () {
    cat > ~jae/.asoundrc.default << EOF
pcm.!default thinkpad_hw
ctl.!default thinkpad
EOF
}

wine () { # nuforce w/o dmix
    cat > ~jae/.asoundrc.default << EOF
pcm.!default winegame
ctl.!default aengine
EOF
}

usage () {
    echo `basename $0` '[wine|nuforce|aengine|thinkpad|auto]'
}

case $output in
    w*|g*) wine ;;
    n*) nuforce ;;
    t*) thinkpad ;;
    a48) aengine48 ;;
    auto|a*) asound-set ;;
    *) usage ;;
esac

