#!/bin/sh

## script to change volume of pulse-audio via command line
## for now only works on the default sink

# this lets it work on systems over ssh
# XDG_RUNTIME_DIR is usally set by the session manager
export XDG_RUNTIME_DIR=/run/user/$(id -u)

sink_name=$(pactl list sinks | awk '/Name:/ { print $2 }')
default_sink=$(pactl list sinks | awk -F\# '/^Sink/ {print $2}')

usage() {
    [ -n "$1" ] && echo "$1"
    echo "Usage: $(basename $0) [command] [percent]"
    echo "Commands:"
    echo "\tm/mute     toggle mute"
    echo "\t+/up       volume up"
    echo "\t-/down     volume down"
    echo "Examples:"
    echo "\t\"$(basename $0) up 10\" - increase volume by 10%"
    echo "\t\"$(basename $0) -5\" - decrease volume by 5%"
    exit 1
}

change=$(echo "$1" | grep -o "[0-9]\+")
[ -n "$2" ] && change="$2"
if [ -z "$change" ]; then
    change=$(( 5 * $(echo $1 | grep -o -- "[+-]" | wc -w) ))
fi

get_vol() {
    lr_volume=$(pactl list sinks | awk '/^\s+Volume:/ { print $5"/"$12 }')
    volume=${lr_volume%%%*}
}
get_vol

set_vol() {
    new_vol_perc="${1}"
    pactl -- set-sink-volume @DEFAULT_SINK@ "${new_vol_perc}"
    get_vol
}

show_vol() {
    if [ -t 0 ]; then
        echo $sink_name
        echo $lr_volume
    else
        if ! dunstify_vol_bar $lr_volume
        then
            notify-send -t 2000 -u low ${lr_volume}
        fi
    fi
}

# only works w/ dunst notification daemon
dunstify_vol_bar(){
    type dunstify > /dev/null || return 1
    bar=$(seq -s "─" $(($volume/5)) | tr -d '0-9')
    icon=audio-volume-high-symbolic
    if [ $volume -lt 33 ]; then icon=audio-volume-low-symbolic
    elif [ $volume -lt 67 ]; then icon=audio-volume-medium-symbolic; fi
    [ $volume -eq 100 ] && space="   " || space="    "
    dunstify -i $icon -r 407 -u low -t 2000 "[$volume]$space$bar"
}

show_mute(){
    if pactl list sinks | grep -q "Mute: yes"
    then
        status="Sound Muted"
    else
        status="Sound Un-muted"
    fi
    if [ -t 0 ]; then
        echo $status
    else
        notify-send -t 2000 -u low ${status}
    fi
}

ceil () { vol="${1%*%}"; chg="$2"
    newvol=$(( $vol + $chg ))
    mod=$(( $newvol - 100 ))
    [ $newvol -gt 100 ] && echo $(( $chg - $mod )) || echo $chg
}

floor () { vol="${1%*%}"; chg="$2"
    newvol=$(( $volume - $chg ))
    [ $newvol -lt 0 ] && echo $(( $chg + $newvol )) || echo $chg
}

case "$1" in
    -h|--help)
        usage
        ;;
    [0-9]*)
        set_vol "${change}%"
        show_vol
        ;;
    [+]*|u*)
        change=$(ceil $volume $change)
        set_vol "+${change}%"
        show_vol
        ;;
    [-]*|d*)
        change=$(floor $volume $change)
        set_vol "-${change}%"
        show_vol
        ;;
    mute|m*)
        pactl -- set-sink-mute @DEFAULT_SINK@ toggle
        show_mute
        ;;
    *)
        show_vol
        show_mute
        ;;
esac


