#!/bin/sh

## script to change volume of pulse-audio via command line
## for now only works on default

# this lets it work on systems over ssh
# XDG_RUNTIME_DIR is usally set by the session manager
export XDG_RUNTIME_DIR=/run/user/$(id -u)

sink_name=$(pacmd stat | awk '/sink name/ { print $4 }')
default_sink=$(pacmd list-sinks | awk '/\* index:/ {print $3}')

volume=$(pacmd dump-volumes \
    | awk -F= "/Sink $default_sink/ { print \$3 }" \
    | awk '{ print $1$4,$8$11}')

usage() {
    [ -n "$1" ] && echo "$1"
    echo "Usage: $(basename $0) [command] [percent-change]"
    echo "Commands:"
    echo "\t+/up       volume up"
    echo "\t-/down     volume down"
    echo "Examples:"
    echo "\t\"$(basename $0) up 10\" - increase volume by 10%"
    echo "\t\"$(basename $0) -5\" - decrease volume by 5%"
    exit 1
}

change=$(echo "$1" | grep -o "[0-9]\+")
[ -n "$2" ] && change="$2"
if [ -z "$change" ]; then
    change=$(( 5 * $(echo $1 | grep -o -- "[+-]" | wc -w) ))
fi

volume=$(pacmd dump-volumes \
    | awk -F= "/Sink $default_sink/ { print \$3 }" \
    | awk '{ print $4 }')

ceil () { vol="${1%*%}"; chg="$2"
    newvol=$(( $vol + $chg ))
    mod=$(( $newvol - 100 ))
    [ $newvol -gt 100 ] && echo $(( $chg - $mod )) || echo $chg
}

floor () { vol="${1%*%}"; chg="$2"
    newvol=$(( $volume - $chg ))
    [ $newvol -lt 0 ] && echo $(( $chg + $newvol )) || echo $chg
}

# strip off number if it was right against modifier (eg. +10)
cmd=$(echo "$1" | sed 's/[0-9]\+//g')
case "$cmd" in
    -h|-?)
        usage
        ;;
    [+]*|u*)
        change=$(ceil $volume $change)
        pactl -- set-sink-volume ${default_sink} +${change}%
        ;;
    [-]*|d*)
        change=$(floor $volume $change)
        pactl -- set-sink-volume ${default_sink} -${change}%
        ;;
esac

# final volume
if [ -t 0 ]; then
    echo $sink_name
    pacmd dump-volumes \
        | awk -F= "/Sink $default_sink/ { print \$3 }" \
        | awk '{ print $4"/"$11}'
else
    pacmd dump-volumes \
        | awk -F= "/Sink $default_sink/ { print \$3 }" \
        | awk '{ print $4"/"$11}' \
        | notify-send -t 10 -u low $(cat)
fi
