#!/bin/zsh

usage () {
    echo "Usage: `basename $0` COMMAND [options]"
    echo "COMMANDs:"
    echo "usb    - sync all music to usb drive (/media/data)"
    echo "hd     - sync goodlist playlist songs to local drive."
    echo "player - sync goodlist playlist songs to Sansa."
}
short-usage () {
    echo "hd player usb"
}

# playlists for HD/USB syncs (not player, no room)
playlists=( ~/.mpd/playlists/goodsongs.m3u
            ~/.mpd/playlists/angrysongs.m3u
            ~/.mpd/playlists/chillsongs.m3u )
# 'player' still hardcoded to goodsongs.m3u below

# take all current songs in playlist, hardlink to a tmp dir and swap dirs
rm_old () {
    set -e
    src=$1
    [ -d "$src" ] || { echo "Missing source directory"; usage; exit 1; }

    olddir="$src/old"
    [ -d "$olddir" ] && { echo "$olddir alredy exists!"; exit 1 }
    mkdir $olddir

    mv $src/artists $src/mixed $olddir/

    (
        cd $olddir
        for playlist in $playlists; do
            cat $playlist | while read f ; do
                cp --link --parent "$f" "$src/"
            done
        done
    )

    [ -d $olddir ] && rm -rf $olddir
}

case "$1" in
    usb)
        MOUNT=/media/data/music
        echo "Verify mount ($MOUNT):"
        mount | grep media
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        rsync -vaiz --progress --size-only --delete \
            /share/public/music/{artists,mixed,jazz} $MOUNT/
        ;;
    hd)
        MOUNT=/share/public
        echo "Verify NFS mount ($MOUNT):"
        mount | grep "^nfs"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        set -e
        for playlist in $playlists; do
            rsync -viz --size-only --progress --delete \
                --files-from $playlist $MOUNT/music /home/jae/shelf/music
        done
        rm_old /home/jae/shelf/music
        ;;
    player)
        MOUNT=/media/data/sdd
        echo "Verify mount: ($MOUNT)"
        mount | grep "$MOUNT"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        PLAYLIST=${HOME}/.mpd/playlists/goodsongs.m3u
        DEST=$MOUNT/MUSIC/playlist
        cp $PLAYLIST $DEST
        #sed -i 's/4a$/p3/g' $DEST/goodsongs.m3u 2> /dev/null
        rsync -viz --progress --size-only --delete \
            --delete-before \
            --files-from $DEST/goodsongs.m3u \
            /share/public/music $DEST/
        sed -i 's/\//\\/g' $DEST/goodsongs.m3u 2> /dev/null
        # eliminate old songs
        ${HOME}/.mpd/sort-good
        cwd=`pwd`
        cd $DEST/
        find artists mixed -type f | while read f ;
            do look "$f" $PLAYLIST > /dev/null || echo -n "$f\0" ;
        done | xargs -0 -r rm
        cd $cwd
        ;;
    list) short-usage ;;
    *) usage ;;
esac


