#!/bin/zsh

usage () {
    echo "Usage: `basename $0` COMMAND [options]"
    echo "COMMANDs:"
    echo "usb    - sync all music to usb drive (/media/data)"
    echo "hd     - sync goodlist playlist songs to local drive."
    echo "player - sync goodlist playlist songs to FiiO."
}
short-usage () {
    echo "hd player usb"
}

# playlists for HD/USB syncs (not player, no room)
playlists=( ~/.mpd/playlists/goodsongs.m3u
            ~/.mpd/playlists/angrysongs.m3u
            ~/.mpd/playlists/chillsongs.m3u )
# 'player' still hardcoded to goodsongs.m3u below

# take all current songs in playlist, hardlink to a tmp dir and swap dirs
rm_old () {
    set -e
    setopt extendedglob
    src=$1
    [ -d "$src" ] || { echo "Missing source directory"; usage; exit 1; }

    olddir="$src/old"
    [ -d "$olddir" ] && { echo "$olddir alredy exists!"; exit 1 }
    mkdir $olddir

    # "^old" means not-old or all-but-old in zsh
    mv $src/^old $olddir/

    (
        cd $olddir
        for playlist in $playlists; do
            cat $playlist | while read f ; do
                cp --link --parent "$f" "$src/"
            done
        done
    )

    [ -d $olddir ] && rm -rf $olddir
}

case "$1" in
    usb)
        MOUNT=/media/data/music
        echo "Verify mount ($MOUNT):"
        mount | grep media
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        rsync -vaiz --progress --size-only --delete \
            /share/public/music/{artists,mixed,jazz} $MOUNT/
        ;;
    hd)
        MOUNT=/share/public
        echo "Verify NFS mount ($MOUNT):"
        mount | grep "^nfs"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        set -e
        for playlist in $playlists
        do
            echo "Syncing $playlist"
            rsync -viz --size-only --progress --delete \
                --files-from $playlist $MOUNT/music /home/jae/shelf/music
        done
        rm_old /home/jae/shelf/music
        ;;
    player)
        MOUNT=$(df | grep /media/data | iselect -af -p 9 | awk '{print $6}')
        echo "Verify mount: ($MOUNT)"
        mount | grep "$MOUNT"
        echo Press Enter to continue Ctrl-C to abort.; read ignore
        for playlist in $playlists
        do
            echo "Syncing $playlist"
            DEST=$MOUNT/playlist
            cp $playlist $DEST
            rsync -viz --progress --size-only --delete \
                --delete-before \
                --files-from $playlist /share/public/music $DEST/
            sed -i 's/\//\\/g' $DEST/$playlist 2> /dev/null
        done
        ;;
    list) short-usage ;;
    *) usage ;;
esac

sync
