#!/bin/sh

dedupdir="./deduped"
mkdir -p $dedupdir

dupdir="./dups"
mkdir -p $dupdir

count=0
while read file;
do
    [ -n "$file" ] || continue
    count=$(($count + 1))
    md5=$(md5sum -b $file | awk '{print $1}')
    suffix=${file##*.}
    dest="${dedupdir}/${md5}.${suffix}"
    if [ -e ${dest} ]; then
        mv $file ${dupdir}
        echo "skipping duplicate ($count)"
        continue
    fi
    echo "mv $file ${md5}.${suffix} ($count)"
    mv $file ${dest}
done

echo "Deduped files in $dedupdir"
echo "$count originals; $(ls $dedupdir | wc -l) deduped"
