#!/bin/sh

### Small terminal to (run and) display command output.

usage () {
    echo "Usage: `basename $0` [options]"
    echo "Options:"
    echo "\t-f focus window"
    echo "\t-b border color"
    echo "\t-g geometry"
    echo "\t-o opacity"
    echo "\t-t title"
    echo "\t-h help"
    exit
}

border=rgb:44/44/44
title="$@"
opacity=00

while getopts fb:g:o:t:h arg; do
    case $arg in
        f) focus=true; shift;;
        b) border="$OPTARG"; shift; shift;;
        g) geom=$OPTARG; shift; shift;;
        o) opacity="$OPTARG"; shift; shift;;
        t) title=$OPTARG; shift; shift;;
        h) usage;;
    esac
done

cmd="$@"

height=3
width=64
res_width=2560
y=0
x=$((res_width-(width*10)))

# if not specified, draw in upper right corner, top down, fill in blank spots
if [ -z "$geom" ]; then
    count=$(xdotool search --onlyvisible --classname cmd-term | wc -l)
    num=0
    if [ "$count" -gt 0 ]; then
        # generate list of y coords of existing cmd-terms
        tmp=$(mktemp)
        trap "rm -f ${tmp}; exit" 2 0
        for id in $(xdotool search --onlyvisible --classname cmd-term); do
            xwininfo -id $id | awk -F+ '/geometry/ {print $2}' >> ${tmp}
        done
        sort -n -o ${tmp} ${tmp}

        # this will loop through y positions of existing cmd-terms
        # finds gap or appends to end
        for a_y in $(cat ${tmp}); do
            if [ "$(( $a_y / 42 ))" -gt $num ]; then
                break
            fi
            num=$(( $num + 1 ))
        done
        rm -f ${tmp} # trap doesn't seem to work reliably
    fi

    y=$(( $num * 50 ))
    geom=${width}x${height}-${x}+${y}
else
    echo "here, $geom"
    set -- $(printf "$geom" \
        | sed -E 's/([0-9]+)x([0-9]+)([-+][0-9]+)?([+-][0-9]+)?/\1 \2 \3 \4/')
    width=$1
    height=$2
    [ -n "$3" ] && x=$3
    [ -n "$4" ] && y=$4
    echo $width $height $x $y
fi

[ -n "$focus" ] && name='focused-cmd-term' || name='cmd-term'

[ -n "$SHELL" ] || SHELL=/bin/sh

if type alacritty > /dev/null
then
    exec alacritty --class $name \
        --config-file ~/.config/alacritty/cmd-term.yml \
        -o window.position.x=${x} -o window.position.y=${y} \
        -o window.dimensions.columns=${width} \
        -o window.dimensions.lines=${height} \
        -e $SHELL -c "$cmd" &
elif type urxvt > /dev/null
then
    rxvt="urxvt"
    pgrep urxvtd > /dev/null && rxvt="urxvtc"
    exec $rxvt -fn terminus-16 -name $name -title "$title" \
        -geometry "${geom}" -bl -b 0 -bd "$border" -cr grey \
        -depth 32 -fg grey -bg "[${opacity}]#2d2d2d" \
        -e $SHELL -c "$cmd" &
else # terminal lowest common denominator
    exec x-terminal-emulator -fn terminus-16 -name $name -title "$title" \
        -geometry "${geom}" -b 1 -cr grey \
        -e $SHELL -c "$cmd" &
fi

