#!/bin/sh

usage () {
    echo "Usage: `basename $0` [options]"
    echo "Options:"
    echo "\t-f focus window"
    echo "\t-b border color"
    echo "\t-g geometry"
    echo "\t-o opacity"
    echo "\t-t title"
    echo "\t-h help"
    exit
}

border=rgb:44/44/44
title="$@"
opacity=00

while getopts fb:g:o:t:h arg; do
    case $arg in
        f) focus=true; shift;;
        b) border="$OPTARG"; shift; shift;;
        g) geom=$OPTARG; shift; shift;;
        o) opacity="$OPTARG"; shift; shift;;
        t) title=$OPTARG; shift; shift;;
        h) usage;;
    esac
done

# if not specified, draw in upper right corner, top down
if [ -z "$geom" ]; then
    num=$(xdotool search --onlyvisible --classname cmd-term | wc -l)
    y=$(( $num * 50 ))
    geom=64x3-0+${y}
fi
[ -n "$focus" ] && name='focused-cmd-term' || name='cmd-term'

[ -n "$SHELL" ] || SHELL=/bin/sh

#-pixmap "${HOME}/.themes/Wallpaper/pennyarcade_bkgd.png;0+0+0:op=tile" \
if type urxvt
then
    exec urxvt -fn terminus-16 -name $name -title "$title" \
        -geometry "${geom}" -bl -b 0 -bd "$border" -cr grey \
        -depth 32 -fg grey -bg "[${opacity}]#2d2d2d" \
        -e $SHELL -c "$@"
else # terminal lowest common denominator
    exec x-terminal-emulator -fn terminus-16 -name $name -title "$title" \
        -geometry "${geom}" -b 1 -cr grey \
        -e $SHELL -c "$@"
fi

