#!/bin/sh

usage () {
    echo "Usage: `basename $0` [options]"
    echo "Options:"
    echo "\t-t title"
    echo "\t-g geometry"
    echo "\t-b border color"
    echo "\t-f focus window"
    echo "\t-h help"
    exit
}

border=rgb:44/44/44
title="$@"

while getopts ft:b:g:h arg; do
    case $arg in
        t) title=$OPTARG; shift; shift;;
        g) geom=$OPTARG; shift; shift;;
        b) border="$OPTARG"; shift; shift;;
        f) focus=true; shift;;
        h) usage;;
    esac
done

if [ -z "$geom" ]; then
    num=$(xdotool search --onlyvisible --classname cmd-term | wc -l)
    y=$(( $num * 50 ))
    geom=64x3-0+${y}
fi
[ -n "$focus" ] && name='focused-cmd-term' || name='cmd-term'

exec x-terminal-emulator -fn terminus-16 -name $name -title "$title" \
    -geometry "${geom}" -bl -b 1 -bd "$border" -cr grey \
    -pixmap "${HOME}/.themes/Wallpaper/pennyarcade_bkgd.png;0+0+0:op=tile" \
    -e sh -c "$@"
