#!/bin/sh

dim=$(stty size)
width=${dim##* }
height=${dim%% *}

cmd=`basename $0`
chg=12
[ -n "$1" ] && chg="$1"
if [ $cmd = "short" ] ; then 
    height=$(( $height-$chg ))
else
    height=$(( $height+$chg ))
fi

/usr/bin/xtermset -geom ${width}x${height}

