#!/bin/sh

set -e -u

cmd=$(basename $0)
chg=12
mult=1
[ "$#" -gt 0 ] && [ -n "$1" ] && mult="$1"
[ "$mult" -gt 5 ] && { echo "bad multipler"; exit 1; }
padding=$((6 * 2))

tty_dim=$(stty size)
tty_height=${tty_dim%% *}
win_height=$(xwininfo -id "$(xdotool getwindowfocus)" | awk '/Height:/ {print $2}')
# need actual text rendering area, so subtrace padding (+1 for round up)
win_height_adj=$((win_height - padding + 1))
row=$((win_height_adj/tty_height))

tty_width=${tty_dim##* }
win_width=$(xwininfo -id "$(xdotool getwindowfocus)" | awk '/Width:/ {print $2}')
win_width_adj=$((win_width - padding + 1))
column=$((win_width_adj/tty_width))

new_win_width=-1
case $cmd in
    big)
        new_win_height=$((row * 36 + padding))
        new_win_width=$((column * 84 + padding))
        ;;
    small)
        new_win_height=$((row * 24 + padding))
        new_win_width=$((column * 84 + padding))
        ;;
    short*)
        new_win_height=$((win_height - (row * (chg*mult)) + 6))
        ;;
    tall*)
        new_win_height=$((win_height + (row * (chg*mult))))
        ;;
esac

wmctrl -r ":ACTIVE:" -e 0,-1,-1,$new_win_width,$new_win_height
