#!/bin/sh

# This is almost exclusively for vim diff mode. So 161 wide is for 2 80 column
# text windows plus an extra column for the dividing line.

height=$(stty size | cut -d' ' -f 1)
#echo $height

/usr/bin/xtermset -geom 161x$height

