#!/bin/sh

usage () {
    echo usage: `basename $0` [-hl] [times [interval]]
    echo "\t-b       - background and log output to /tmp/fetchmail.out"
    echo "\t-h       - this help"
    echo "\ttimes    - number of times to get mail (default 20)"
    echo "\tinterval - time (secs) to sleep b/w fetchmail calls (default 300)"
    exit
}

bkgrd=
while getopts bh arg; do
    case $arg in
        b) bkgrd=yes; shift
            ;;
        h) usage
            ;;
    esac
done

# default to every 5 minutes for 12 times (1/5min for 1 hour)
[ -n "$1" ] && times="$1" || times=12
[ -n "$2" ] && intvl="$2" || intvl=300

# make sure params are set from now on
set -e -u

script='\
times="$1"
intvl="$2"
bkgrd="$3"

[ -d "$TMPDIR" ] || TMPDIR="/tmp"
[ -d "$TMP" ] && TMPDIR=$TMP

umask 077

lock=$TMPDIR/fetchmail-loop.lock
lockfile -r0 $lock || exit 1
trap "rm -f $lock" 0
trap "exit" 2

log=$TMPDIR/fetchmail.out
if [ -n "$bkgrd" ]; then
    chmod 700 $log
    echo -n > $log
    exec 1> $log 2>&1
fi

biff init

while [ $times -gt 0 ] ; do
    echo "Getting mail..."
    fetchmail 2>&1 | grep --line-buffered -v "^INFO: LOG"
    times=$((${times}-1))
    biff check
    echo -n "... ($times times left) ... "
    [ $times -gt 0 ] && sleep $intvl
done

biff fini

echo
echo ...............done
'
if [ -n "$bkgrd" ] ; then
    exec sh -c "$script" fetchmail-loop $times $intvl yes &
else
    exec sh -c "$script" fetchmail-loop $times $intvl
fi

