#!/bin/sh

cmd="$1"

ifaces () {
    awk '/^iface/' /etc/network/interfaces | cut -d\  -f 2 \
        | grep -v 'lo\|eth\|wlan\|default'
    echo "eth0\ndown\nstatus\nscan"
}
[ -n "$cmd" ] || { ifaces; exit; }

D="\033[0;31m"
U="\033[1;32m"
status () {
    isup eth0 && echo "${U}eth0 up" || echo "${D}eth0 down"
    if isup wlan0 ; then
        echo -n "${U}wlan0 up on " && /sbin/iwgetid -r || echo "${D}wlan0 down"
        /sbin/iwconfig wlan0 | grep -o 'Link Quality=[0-9/]\+'
        /sbin/iwconfig wlan0 | grep -o 'Power Management:o.\+'
    fi
}

isup () {
    case "$1" in
        wlan0|eth0) ip link show "$1" | grep -q state\ UP ;;
        *) isup eth0 || isup wlan0 ;;
    esac
}

down() {
    dev="$1"
    sudo ifdown "$dev" 2> /dev/null
    sudo ifdown --force "$dev" 2> /dev/null
    sudo ip link set "$dev" down
    sudo iwconfig wlan0 power on
    sudo rfkill block wifi # turn off when not in use
}

downup () {
    down wlan0 2> /dev/null
    ifup_watch "$1"
}

ifup_watch () {
    sudo rfkill unblock wifi # enable wifi
    sudo iwconfig wlan0 power off # power management causes drops
    sudo ifup "$1"
    #sudo ifup --verbose "$1"
    [ "${1%=*}" = "wlan0" ] || return
    while ! /sbin/iwgetid > /dev/null ; do
        echo -n . ; sleep 1
    done ; { echo -n ' connected to '; /sbin/iwgetid -r ;} | hl '.*'
}

wpa () {
    [ -n "$1" -a -n "$2" ] || { echo "missing ssid/psk args"; exit 1; }
    ssid="$1"; psk="$2"
    sudo sh -c \
        "wpa_passphrase $ssid $psk >> /etc/wpa_supplicant/wpa_supplicant.conf"
    ifup_watch wlan0
}

proxy_setup () {
    touch /tmp/use-roaming-resolv-conf
    trap '{ sleep 3; rm -f /tmp/use-roaming-resolv-conf; } &' 0
}

scan (){
    sudo rfkill unblock wifi # enable wifi
    if ! isup wlan0 ; then
        sudo ip link set wlan0 up
        trap 'sudo ip link set wlan0 down' 0
    fi
    sudo iwlist wlan0 scan
}

case $cmd in
wpa) wpa $2 $3 ;;
proxy|pro*) proxy_setup; ifup_watch wlan0 ;;
wlan*|roam|r*|up|u*|on) ifup_watch wlan0 ;;
down|off|of*) { down wlan0; } ;;
stat|st*) status ;;
scan|sc*) scan ;;
*) ifup_watch wlan0=$cmd ;;
esac

